### ISSUE TITLE
error occurs when running the node

### ISSUE THREAD

**Issue by keetsky** [kunle12/dn_object_detect#1]
I have  download the model/weights file separately, and put it in the darknet directory ；then roslaunch dn_object_detect objdetect.launch,but error occurs ,that is :[ERROR] [1480756104.343588240]: Unable to find YOLO darknet configuration or model files. what's wrong with it?

**Comment by kunle12** [comment]
You should change the yolo_config and yolo_model parameters in the launch file and point them to the directory where you store the yolo cfg and weights files.

**Comment by kunle12** [comment]
I assume that it is working for you and close this issue.
