### ISSUE TITLE
undefined reference to `demo_yolo'

### ISSUE THREAD

**Issue by mbjelonic** [kunle12/dn_object_detect#2]
Hi, 
I receive the following error after I try to build the ros package:

```
Errors     << dn_object_detect:make /home/markob/any_ws/logs/dn_object_detect/build.make.001.log                                                                                                                                                      
/home/markob/any_ws/src/dn_object_detect/lib/libyololib.so: undefined reference to `demo_yolo'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/markob/any_ws/devel/.private/dn_object_detect/lib/dn_object_detect/dn_object_detect] Error 1
make[1]: *** [CMakeFiles/dn_object_detect.dir/all] Error 2
make: *** [all] Error 2
cd /home/markob/any_ws/build/dn_object_detect; catkin build --get-env dn_object_detect | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```
Can you help me with this error? 

In addition, I disabled the GPU line in the Makefile of darknet by setting GPU=0. Is your code also working on the CPU without the CUDA dependencies?

Thank you in advance.

Best,
Marko

**Comment by CEfanmin** [comment]
I have the same problem too! do you get the answer? Thanks

**Comment by kunle12** [comment]
If you use the patched darknet code included as a submodule in this repository, you should not encounter this error. I haven't tried to compile without CUDA. I should when I get some spare time.

**Comment by mbjelonic** [comment]
I used the patched darknet code and I followed the instructions in the readme.

**Comment by kunle12** [comment]
I am unable to reproduce your error. I use the following commands to do a successful build.
Assume a working catkin workspace called /home/kunle12/dev/catkin_ws

```
cd  /home/kunle12/dev/catkin_ws/src
git clone --recursive https://github.com/kunle12/dn_object_detect
cd dn_object_detect/darknet/
mkdir build;cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/kunle12/dev/catkin_ws/src/dn_object_detect ..
make install
cd ../../..
catkin_make dn_object_detect

```
