### ISSUE TITLE
Can modify darknet_ros subscribe the datatype of the image format ? I want to use the format of sensor_msgs/CompressedImage rather than sensor_msgs/Image

### ISSUE THREAD

**Issue by sunt40** [kunle12/dn_object_detect#9]

**Comment by kunle12** [comment]
the image transport subscriber is already using compress transport hints. If you have proper image transport compression package installed and used in the publisher. The node will automatically use compressed image

see http://wiki.ros.org/image_transport#image_transport_Subscribers for details.

**Comment by sunt40** [comment]
Now the situation is that I use `rosrun image_transport republish [in_transport] in:=<in_base_topic> [out_transport] out:=<out_base_topic>` to convert the datatype of the Image to sensor_msgs /Image. The Darknet node can subscribe to this Image topic but cannot read the Image.

**Comment by kunle12** [comment]
I am not sure why you want to convert/use the raw image, if your camera node can only produce raw sensor_msgs/Image, you should use the image_transport to convert to compressed image and then use dn_object_detect node, e.g. ```rosrun image_transport republish raw in:=/usb_cam/image_raw compressed out:=/test_transport/image_compressed``` and then have dn_object_detect to subscribe to ```/test_transport/image_compressed```.

Having said the above, if you insist to have dn_object_detect to use raw image, you can make a small code change to ```src/MultiClassObjectDetector.cpp``` line 300, replacing "compressed" with "raw" and recompile the code.

**Comment by sunt40** [comment]
Did you use darknet_ros ? It uses raw images.But I want it to use compressed images. I have modified darknet_ros to subscribe compressed images topic. But it shows "waiting images", It looks like imagecallback fuction has some problem. I didn't modify the imagecallback function after modifying the subscribe code. Do you have some advice ? Maybe I should modify imagecallback fuction???

**Comment by kunle12** [comment]
No. ```dn_object_detect``` is not related to darknet_ros package at all. I use my own custom/modified version of darknet library. If you want to use darknet_ros, you are talking to the wrong person/code owner. I don't know or use darknet_ros. In case you indeed want to use ```dn_object_detect``` i.e. this repository, you need to follow the README instructions in this repo and build the code.  ```dn_object_detect```  supports compressed image format out of box. Just need to hook the node with proper image source node e.g. usb_cam node.
